### ISSUE TITLE
TypeError: Cannot read property 'topologyRoot' of null

### ISSUE THREAD

**Issue by fferner** [infiniband-radar/infiniband-radar-daemon#7]
All,

I'm currently trialing this on one of our fabrics and after some trial end error to on the config side and order of starting daemon vs web containers, I've got something up. I see data appearing in the grafana dashboards.

Unfortunately the fabric view is not showing any data and in the logs for the infinibandradarweb_api I see this error:

```
[Tue, 17 Dec 2019 17:19:18 GMT][Debug][ApiServer] Took 6 ms to process (GET) '/api/v2/topologies/cs04r' StatusCode: 500
TypeError: Cannot read property 'topologyRoot' of null
    at TopologiesController.<anonymous> (/home/node/server/src/api/v2/controllers/TopologiesController.ts:44:89)
    at step (/home/node/server/src/api/v2/controllers/TopologiesController.ts:58:23)
    at Object.next (/home/node/server/src/api/v2/controllers/TopologiesController.ts:39:53)
    at fulfilled (/home/node/server/src/api/v2/controllers/TopologiesController.ts:30:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

In context, this seems to be the relevant section of the log:

```
[Tue, 17 Dec 2019 17:19:01 GMT][INFO][TopologiesController] [cs04r] Got first topology version
[Tue, 17 Dec 2019 17:19:01 GMT][Debug][ApiServer] Took 53 ms to process (PUT) '/api/v2/topologies/cs04r' StatusCode: 204
[Tue, 17 Dec 2019 17:19:01 GMT][INFO][TopologyOptimizerService] [cs04r] Start optimization
[Tue, 17 Dec 2019 17:19:06 GMT][Debug][ApiServer] Took 46 ms to process (PUT) '/api/v2/metrics/cs04r' StatusCode: 204
[Tue, 17 Dec 2019 17:19:11 GMT][Debug][ApiServer] Took 46 ms to process (PUT) '/api/v2/metrics/cs04r' StatusCode: 204
[Tue, 17 Dec 2019 17:19:16 GMT][Debug][ApiServer] Took 28 ms to process (PUT) '/api/v2/metrics/cs04r' StatusCode: 204
[Tue, 17 Dec 2019 17:19:16 GMT][Debug][ApiServer] Took 2 ms to process (GET) '/api/v2/login/loginConfig' StatusCode: 304
[Tue, 17 Dec 2019 17:19:16 GMT][Debug][ApiServer] Took 1 ms to process (GET) '/api/v2/fabrics' StatusCode: 304
[Tue, 17 Dec 2019 17:19:17 GMT][Debug][ApiServer] Took 1 ms to process (GET) '/api/v2/config' StatusCode: 304
[Tue, 17 Dec 2019 17:19:18 GMT][Debug][ApiServer] Took 6 ms to process (GET) '/api/v2/topologies/cs04r' StatusCode: 500
TypeError: Cannot read property 'topologyRoot' of null
    at TopologiesController.<anonymous> (/home/node/server/src/api/v2/controllers/TopologiesController.ts:44:89)
    at step (/home/node/server/src/api/v2/controllers/TopologiesController.ts:58:23)
    at Object.next (/home/node/server/src/api/v2/controllers/TopologiesController.ts:39:53)
    at fulfilled (/home/node/server/src/api/v2/controllers/TopologiesController.ts:30:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by fferner** [comment]
Interestingly, overnight docker-ce got updated on the host running the web/mongodb etc containers. I deleted them and restarted them and now this seems to work. I've also noticed this seems pretty much the same as #5 so I think I'll close this issue.
